# Generated by Django 4.2.7 on 2026-02-22 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percentage', models.FloatField(default=0.0)),
                ('matched_skills_count', models.PositiveIntegerField(default=0)),
                ('total_required_skills', models.PositiveIntegerField(default=0)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('weak_skills', models.JSONField(blank=True, default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='opportunities.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Match Result',
                'ordering': ['-match_percentage'],
                'unique_together': {('user', 'opportunity')},
            },
        ),
    ]
